spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
    show-sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:2s}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
  external-order-event:
    base-url: ${APP_EXTERNAL_ORDER_EVENT_BASE_URL:}
    path: ${APP_EXTERNAL_ORDER_EVENT_PATH:}
  mock-order-event:
    enabled: false
  kafka-order-event:
    publisher:
      enabled: ${APP_KAFKA_ORDER_EVENT_PUBLISHER_ENABLED:false}
    consumer:
      enabled: ${APP_KAFKA_ORDER_EVENT_CONSUMER_ENABLED:false}
